# Generated by Django 5.0.3 on 2024-04-01 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_field',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
