# Generated by Django 5.0.3 on 2024-04-01 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('name', models.CharField(default='shafi', max_length=20)),
                ('roll', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('address', models.TextField(default='sss')),
                ('duration_field', models.DurationField(default=datetime.timedelta(days=12))),
            ],
        ),
    ]
