# Generated by Django 5.0.3 on 2024-04-01 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_mymodel_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='roll',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='auto_field',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='date_field',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='date_time_field',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='duration_field',
            field=models.DurationField(default=0),
        ),
    ]
