# Generated by Django 5.0.3 on 2024-04-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_release_date', models.DateField(auto_now=True)),
                ('rating', models.IntegerField(choices=[('1', 'ne'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], default=1)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musician.musicianmodel')),
            ],
        ),
    ]
